### ISSUE TITLE
New Beta testing -  GA Readiness

### ISSUE THREAD

**Issue by AV25242** [bwgjoseph/mongoose-vs-ottoman#109]
Hello @bwgjoseph , we released new beta today. 

The request is if you and team can do the regression just like you do always and help us release a GA by end of them month.
We are targeting GA end of the month also depends if nothing major was found (which we hope not). 

Can you assist please ?

**Comment by bwgjoseph** [comment]
Sure, but would have to be sometime later this week/weekend

**Comment by AV25242** [comment]
Yeah thanks, appreciate your quick response. Sooner will help us mitigate critical issues if any and do a GA possibly

**Comment by bwgjoseph** [comment]
So I'm trying to upgrade to beta.9 and test out the features, but I've encountered some issue immediately after upgrading.

So this is at beta.8, running [this specific test case](https://github.com/bwgjoseph/mongoose-vs-ottoman/blob/ff9f489f2607ff3dc517faf668a3087e3b74810a/test/ts/%24ignoreCase.test.ts#L60) and it works just fine

![image](https://user-images.githubusercontent.com/37484538/134771513-9de69efd-856e-4e22-bc68-de09edd8762c.png)

Once I upgrade to beta.9, it throws me this when I run the same test

![image](https://user-images.githubusercontent.com/37484538/134771666-30166a81-86fa-47cd-b2b0-01c3998f76f3.png)

And that is referring to the `query` method in this [method](https://github.com/bwgjoseph/mongoose-vs-ottoman/blob/ff9f489f2607ff3dc517faf668a3087e3b74810a/test/ts/setup/util.ts#L10) which I have no idea why it throws error.

So to try to continue, I removed that method, and I face with yet another issue

![image](https://user-images.githubusercontent.com/37484538/134771719-6a98f795-0d8b-4907-90a2-caa8c1eeac89.png)

Which I have no clue what is causing it.

I can't continue to test it for now, until I figured out something myself later on, or if you could provide me with some solution/workaround?

Also, as there are quite a bit of changes since beta.8, I'm not sure what has changed, and there's no changelog, and it's a little bit difficult to trace.

**Comment by AV25242** [comment]
Thanks Joseph, I think this is a more common question asked and the answer is that ottoman.connect is now async 
the docs have been updated to reflect this change 
https://ottomanjs.com/#installation

I 100% agree that there is no change-log but rest assured we are working on getting it and it will be there with release post GA

**Comment by bwgjoseph** [comment]
Thanks, adding the `await` seem to solved it. So the `query` issue is also because there's no connection, hence, the error.

Should have crossed my mind, I remember seeing that changes. 

I should be able to proceed to test the rest of it now. Thanks!
