### ISSUE TITLE
transaction support nodejs sdk, ottoman

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#30]
Hi,

Was wondering when would the support for `transaction` comes for `nodejs sdk` and whether `ottoman` would also support after it lands on `nodejs sdk`

Currently, based on the docs, it seem that only [java-sdk](https://docs.couchbase.com/server/7.0/learn/data/transactions.html) supports it

Thanks

**Comment by AV25242** [comment]
Hello @bwgjoseph, yes transactions for Nodejs will be supported but as you know Nodejs depends on our C library (libcouchbase) so that will be our primary focus first to get transactions for C SDK.  The tentative plans for Nodejs SDK Transactions is end of 2021, we will see after that for a fit in Ottoman :)

**Comment by bwgjoseph** [comment]
Alright, will take note of this. Thanks!
