### ISSUE TITLE
support for schema options - unique

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#47]
Hi,

Does ottoman support unique index currently? See https://mongoosejs.com/docs/api.html#schematypeoptions_SchemaTypeOptions-unique

Thanks

**Comment by AV25242** [comment]
In a way, via ref-doc Indexes

**Comment by bwgjoseph** [comment]
Alright, will test it out, and come back for further questions later

**Comment by bwgjoseph** [comment]
Wish to clarify something about `refDoc` index

Based on the description in [here](https://ottomanjs.com/guides/schema.html#refdoc), and I quote

> They allow only a single document to occupy any particular value and do direct key-value lookups using a referential document to identify a matching document in Couchbase.

What does it mean exactly? 

Does it mean that given this schema

```js
const UserSchema = new Schema({
  name: String,
  email: String,
  card: {
    cardNumber: String,
    zipCode: String,
  },
  roles: [{ name: String }],
});
```

I can create a `refDoc` of any field in the schema

```js
// name, card, roles, email?
UserSchema.index.findRefCard = { by: 'card', type: 'refdoc' };
```

And then I can query as such

```js
const userRefdoc = await User.findRefCard(userData.card);
```

But `userData.card` is an object, so would that be

```js
const userRefdoc = await User.findRefCard(userData.card.cardNumber);
// or
const userRefdoc = await User.findRefCard(userData.card.zipCode);
```

How does it work against `object` or `array` type of field?

And when would I want to use it over `n1q1` index? Especially since that `refDoc` is not maintained by `couchbase`

**Comment by AV25242** [comment]
@bwgjoseph couchbase server as such doesn't impose any schema constraints so the onus is on Ottoman to handle it.
in the case of Unique constraint the way its handled (only via KV / Data service)  is by creating a corresponding binary lookup document corresponding to your original document for each field that you chose as unique. 
the binary document will have a lookup by id to your original document. that way behind the scene when you say call findByName it basically looks for a binarydocument in the database that has the name and pulls the Idkey associated with it and fetches the originaldocument. Since its a KV lookup its pretty fast.  Also note that if you use a query service to update a unique key it doesnt update the binary document as such so the constraint is not to go and update fields manually but use Ottoman to do the operation - So thats on how it works.

On your questions I will get back to you, those are great questions.  Might have to try them out at an object / array level

**Comment by bwgjoseph** [comment]
What do you mean by `binary lookup document`?

So if I'm getting you correctly, say the field is `name`

| Name | Id |
| --- | --- |
| a | 12345 |
| b | 23456 |

So whenever I look for `a`, it has the KV store which maps to `12345` which then grabs the entire document? And if I were to create another document with `a`, it would violate this `unique` constraint and that it would throw error back?

I don't quite get this statement, if you could give a dumber version for me, it would be excellent.

> Also note that if you use a query service to update a unique key it doesnt update the binary document as such so the constraint is not to go and update fields manually but use Ottoman to do the operation

---

Sure, so I have a couple of question on my original post (in case it wasn't clear)

1. How does `refDoc` works against object or array type of field?
2. And when would I want to use it over `n1q1` index? Especially since that `refDoc` is not maintained by `couchbase
3. I was reading [create-right-index-get-right-performance](https://blog.couchbase.com/create-right-index-get-right-performance/), how does the indexes like provided in `Ottoman` map against those listed in the document? 

Thanks!

**Comment by AV25242** [comment]
I am going to attempt again to explain ref-doc Indexes here in detail.

Unique Indexes in Couchbase doesn't exist today, so to provide uniqueness for certain fields within a document as an example say email-address a ref-doc Index is used. 

`What do I mean by ref-doc Index ?`
So say you have 3 documents 
```
document 1
{
   name : "John doe",
   email : "jd@xyz.com",
   age: 52
   id : 1000
}
document 2
{
   name : "Bob Roy",
   email : "br@xyz.com",
   age: 58
   id : 2000
}
document 3
{
   name : "Benny Rogers",
   email : "bn@xyz.com",
   age: 40
   id : 3000
}

```
You need to have a unique field on email you will create a refdoc-index on email address. What this is going to do is it will create 3 additional binary document 

| email **(key)** | Id |
| --- | --- |
| jd@xyz.com | 1000 |
| br@xyz.com | 2000 |
| bn@xyz.com | 3000 |

These documents are **created by Ottoman** (important to know/remember) as `binary documents` and its sole purpose is lookup and its key (remember key guarantees uniqueness and will be unique per document) will be the email.

So if I am now asking for a document by calling UserModel.findByEmail('bn@xyz.com') (**where findByEmail is the name of my Index**) its basically going and looking for a binary doc with that key and look for the Id equivalent in this case its 3000.
Next its going to go and find the actual document in the with Id 3000 and get back the Original document 

```
{
   name : "Benny Rogers",
   email : "bn@xyz.com",
   age: 40
   id : 3000
}
```

These binary documents are ONLY MANAGED via Ottoman. i.e  if you go outside Ottoman for example if you go  to couchbase console (WEB UI) and create a document manually (document 4) say with email `joseph@xyz.com` you will NOT see a binary document created which also means that at this point uniqueness for a document with `joseph@xyz.com` is not guaranteed.
i.e you can go to Ottoman and create document number 5 with email address `joseph@xyz.com` and it will not complain but create the document and this is because a binary-document with this key does not exist.

Likewise if you go and write a N1QL Query and create document 6 with email `av@xyz`  either via UI or Ottoman N1QL query feature a binary-document will NOT be created.  Binary document is the driver here that helps trigger unique index exception on the field (that is internally a key on the binary document). So basically unique key is made available to you via binary-documents. if you use any of Ottoman functions like UpdateMany, CreateMany, replaceByid, updateByid etc to mutate a document we take care of the binary-document for you behind the scene. You need to use ref-doc index wisely and with extreme caution (i.e be aware of what you are doing) or-else binary-document and your original document can go out of sync i.e if you are using Ottoman mutation functions and stay strictly in the realm of Ottoman you are good.

**Comment by AV25242** [comment]
1. How does `refDoc` works against object or array type of field?
   ` Will get back to you on this.`
2. And when would I want to use it over `n1q1` index? Especially since that `refDoc` is not maintained by `couchbase.
 
    ```
N1QL Indexes are not to be mixed up with ref-doc index. A think like ref-doc Index doesnt exist in Couchbase its an Ottoman thing, split the word ref and doc its basically a reference document to your original document and hence the name :)
    
      To your question when will I use N1QL Index. Its where-ever you would like to do a secondary lookup, lookup other than your `key` . For instance you have phone-number or say you want to query by last-name or date-of-birth. you will create an index on these fields (we also call them GSI Index or Secondary Indexes). Once done your find / update via Ottoman that uses N1QL under the hood will be faster.

```
3. I was reading [create-right-index-get-right-performance](https://blog.couchbase.com/create-right-index-get-right-performance/), how does the indexes like provided in `Ottoman` map against those listed in the document? 

`Yeah so those are the Indexes that Couchbase manages, we should be good there.`

**Comment by bwgjoseph** [comment]
Thanks, I was also looking through some past year's Couchbase Connect video and saw your (and Eric) presentation on `Ottoman` and saw the part on `refDoc` and it kinda clicks immediately on the part of a binary document. I never did went into the Web UI and view the document portion but once I saw that it clicks immediately of what it meant.

Your explanation here is excellent too, and it could well go into the `Advance` portion of the docs!

And I was also looking into the other video and had posted a question in the [forum](https://forums.couchbase.com/t/json-data-modeling/30759) if you could, or someone that knows can answer that.

**Comment by AV25242** [comment]
Thanks @bwgjoseph  I have reached out to a group lets see if we get any answer on the forum post.

**Comment by AV25242** [comment]
Did you get the forum post answer, I think thats what this issue is sitting on currently. If so can you please close this one ?

**Comment by bwgjoseph** [comment]
yup, we can close this. Thanks
