### ISSUE TITLE
removeById types

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#71]
Hi,

Seem like the https://github.com/couchbaselabs/node-ottoman/pull/449 did not update `removeById` type

The current one is `removeById(id: string): Promise<any>;`

Should it be `removeById<Result = R>(id: string): Promise<Result>;`? Not sure if it would work

I suppose if changing the declaration to something like this would be much better

```js
interface IModel<T = any, R = T>
```

By default, `R` takes `T` which will be `any` if the type is not defined which is essentially the same as

```js
interface IModel<T = any, R = any>
```

So this would work

`removeById<Result = R>(id: string): Promise<Result>;`

![image](https://user-images.githubusercontent.com/37484538/117395144-01e1e200-af2a-11eb-9d2d-bf4dfd0e5eaf.png)

> alpha.28

**Comment by AV25242** [comment]
Issue created https://github.com/couchbaselabs/node-ottoman/issues/470

**Comment by gsi-alejandro** [comment]
In the next release alpha.29 we will update the result types of `removeById` to look like:
  `removeById(id: string): Promise<{ cas: any }>;`
  
This method always will return an object with a cas property {cas: any}, we don't add generics due to the return always will this one and there isn't the way to change it.

**Comment by httpJunkie** [comment]
Fixed w/ alpha 29

**Comment by bwgjoseph** [comment]
Understand that @gsi-alejandro, thanks!
